### PR TITLE
Fix missing/incorrect weapons

### PR DESCRIPTION
**Pull request by ncraley**
Playing around with this data. Thanks for putting this together!

Noticed a few issues when parsing the data and added some fixes. Let me know if you have any feedback.

Also, for things like the GUO's Doomsday Bell's `"reverberating summons"` keyword, is there an expected field to have for unique weapon keywords' descriptions?

### CODE REVIEW

**Comment by ronplanken** [comment]
Thanks for the additions. I usually add the abilities like the Reverberating summons as an "other" ability. For now that seems to work, not as clean as I would like though.

**Comment by ronplanken** [comment]
@ncraley Can you let me know when you are done with additions? Then I will do a final review.

**Comment by ncraley** [comment]
Yeah, I'll let you know. I've been noticing new things and adding them as I go through

**Comment by ronplanken** [comment]
Just to let you know, I have added a new bulk of data regarding the leaders of each units. This might mess up your changes though.

**Comment by ncraley** [comment]
@ronplanken Those are all of the changes I noticed pre-FW. I merged in the latest from `main` cleanly, but the diff seems to be picking up a lot of your changes too

**Comment by ncraley** [comment]
@ronplanken moving this to another PR, GitHub is being weird about showing the diff correctly: https://github.com/game-datacards/datasources/pull/4

**Pull request closed without merging**
